### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by andershenja** [baltrad/rave#18]
It is not possible to run the software on Python 3.8 and higher due to some changes in how the extension members are handled.

For example:
>>> import _raveio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: version() method: bad call flags

or
>>> import _rave
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: initialization of _rave raised unreported exception

The PyMethodDef has been used for members like {"xsize",NULL}. This is not possible any longer. Simple solution is to adjust so that it looks like {"xsize", NULL, METH_VARARGS}, but this will probably have to be changed in the future as well.

**Comment by andershenja** [comment]
Corrected in rave-build-29

**Comment by YngveE** [comment]
Unfortunately, this solution does not work in python 3.9. We are looking for a solution, but I think the code will need a major refactoring.
