### ISSUE TITLE
Scansun: Use RXbandwidth (if available) to calculate SunMean

### ISSUE THREAD

**Issue by andershenja** [baltrad/rave#2]
(Moved from trac)
In scansun, the scaling by the receiver bandwidth is calculated using the pulse length as follows:
SunMean?-=10*log10(CWIDTH/meta->pulse);
The value of CWIDTH is 1.2, which Asko and Iwan started to use long time ago. The formula was used, because the attribute was not included in the data, even though the attribute was supported by ODIM. It is now supplied by at least 6 members, including SMHI and FMI. The error caused by the missing RXbandwidth value is rather small, compared to the error caused by other missing attributes (e.g. gain, radar constant). For a 2 us pulse the calculated BW is 600 kHz. For most of FMI's radars, the BW is slightly narrower, producing a 0.1-0.3 dB difference. It would be worthwhile to add support for the RXbandwidth in the next sunscan version.

**Comment by pjukka** [comment]
Looks like this 1649a145dc550465e93455cbaf1a3e129b0f10bb is alredy merged to the master, isn't it?

**Comment by andershenja** [comment]
Fixed!
