### ISSUE TITLE
Check for S.wigos in NODfromSource() if S.wmo is not found

### ISSUE THREAD

**Issue by MilkaRadojevic** [baltrad/rave#46]
Hi @andershenja, @guntherhaase

For new radars, /what/source contain WIGOS instead of WMO identifier. 
Therefore if checking for NOD and WMO identifiers fails, then check for presence of WIGOS should be added to the function [NODfromSource()](https://github.com/baltrad/rave/blob/master/Lib/odim_source.py#L179) to avoid unnecessary  rejection of input file.

**Comment by guntherhaase** [comment]
@MilkaRadojevic Thank you for your feedback! We will get back to you when we have resolved the issue.

**Comment by andershenja** [comment]
Added support in rave-build-71.

**Comment by guntherhaase** [comment]
@MilkaRadojevic, Anders has resolved this issue (see above).

**Comment by MilkaRadojevic** [comment]
Thank you.
I've already included my solution since we had to deploy Cirrus into pre-operational. I will fetch your version for next updated of CIRRUS.
