### ISSUE TITLE
Add how attribute "task_args" for quality field "beamb"

### ISSUE THREAD

**Issue by guntherhaase** [baltrad/rave#58]
Add attribute "task_args" to quality field "beamb" group "/datasetM/dataN/qualityP/how" according to [Cookbook recipe](https://baltrad.github.io/cookbook/cookbook_BEAMB).

The attribute should reflect the product's "beamb" configuration, e.g. "[beamb_defines.py](https://github.com/baltrad/beamb/blob/master/pybeamb/beamb_defines.py)", i.e. the limit of the Gaussian approximation of the main lobe and the threshold for correcting beam blockage.

**Comment by andershenja** [comment]
Added in beamb-build-78
